server:
  port: 12000

spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

gitDir: /var/www/blogs